# Some of the topics covered in this course are:
- Objects : creating Our Own Object
- Attributes and Methods
- @classmethod and @staticmethod
- Encapsulation
- Abstraction
- Private vs Public Variables
- Inheritance
- Polymorphism
- super()
- Object Introspection
- Dunder Methods
- Multiple Inheritance
- MRO - Method Resolution Order